import { auth } from "@clerk/nextjs/server"
import {
  SidebarInset,
  SidebarProvider,
} from "@workspace/ui/components/sidebar"
import { preloadQuery } from "convex/nextjs"
import { Providers } from "@/app/providers"
import { AppSidebar } from "@/components/app-sidebar"
import { api } from "@/convex/_generated/api"
import "@workspace/ui/globals.css"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { userId } = await auth()

  const preloadedProjects = userId
    ? await preloadQuery(api.projects.getProjects, { ownerId: userId })
    : null

  return (
    <html
      className={`${geistSans.variable} ${geistMono.variable} h-full font-sans antialiased`}
      lang="en"
      suppressHydrationWarning
    >
      <body className="flex min-h-full flex-col">
        <Providers>
          {userId && preloadedProjects ? (
            <SidebarProvider>
              <AppSidebar preloadedProjects={preloadedProjects} />
              <SidebarInset>{children}</SidebarInset>
            </SidebarProvider>
          ) : (
            children
          )}
        </Providers>
      </body>
    </html>
  )
}
